"""empty message

Revision ID: f9bc5853eccf
Revises: 40e17244e79f
Create Date: 2015-12-21 00:58:08.184506

"""

# revision identifiers, used by Alembic.
revision = 'f9bc5853eccf'
down_revision = '40e17244e79f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
